# Usa una imagen base de Python 3.12 slim
FROM python:3.12-slim

WORKDIR /app

COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app/src/batalla.py /app/batalla.py

ENV PYTHONUNBUFFERED=1