apiVersion: apps/v1
kind: Deployment
metadata:
  name: battleship
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp  
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: battleship-api
        image: jarex1012/battleship_app:latest
        ports: 
          - containerPort: 5000
        
