apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver-limits
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: timeserver-pod-limits
  template:
    metadata:
      labels:
        pod: timeserver-pod-limits
    spec:
      containers:
      - name: timeserver-container
        image: docker.io/wdenniss/timeserver:3
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 200m
            memory: 250Mi
